#!/usr/bin/env bash
#
# platform-sync.sh — pull the xal platform spec forward into a consuming service.
#
# Realizes the template+sync model of platform ADR-0001 (auth ADR-0009): a service
# vendors a READ-ONLY copy of the platform spec into its own docs/platform/, pinned to a
# platform VERSION. Run from the SERVICE's root directory.
#
# Usage:
#   platform-sync.sh <platform-repo-path>            # vendor/update spec, leave changes unstaged for PR review
#   platform-sync.sh <platform-repo-path> --check    # CI: exit non-zero if the service is behind (drift)
#
# The spec is edited ONLY in the platform repo. Never edit a vendored copy in docs/platform/.
set -euo pipefail

VENDOR_DIR="docs/platform"          # where vendored spec lands in the consumer (relative to CWD)
CONFIG="${VENDOR_DIR}/sync.config"  # records the pinned platform version

die() { printf 'platform-sync: %s\n' "$1" >&2; exit 2; }

[ $# -ge 1 ] || die "usage: platform-sync.sh <platform-repo-path> [--check]"
PLATFORM="${1%/}"
MODE="sync"
[ "${2:-}" = "--check" ] && MODE="check"
[ "${2:-}" = "" ] || [ "${2:-}" = "--check" ] || die "unknown argument: ${2}"

[ -f "${PLATFORM}/VERSION" ]      || die "no VERSION at ${PLATFORM} — is that the platform repo?"
[ -f "${PLATFORM}/sync/manifest" ] || die "no sync/manifest at ${PLATFORM}"
[ -d "${PLATFORM}/spec" ]          || die "no spec/ at ${PLATFORM}"

PLATFORM_VERSION="$(tr -d '[:space:]' < "${PLATFORM}/VERSION")"

# Read manifest (skip comments/blanks) into an array.
manifest=()
while IFS= read -r line; do
  line="${line%%#*}"; line="$(printf '%s' "$line" | tr -d '[:space:]')"
  [ -n "$line" ] && manifest+=("$line")
done < "${PLATFORM}/sync/manifest"
[ ${#manifest[@]} -gt 0 ] || die "manifest is empty"

pinned_version() { [ -f "$CONFIG" ] && sed -n 's/^PLATFORM_VERSION=//p' "$CONFIG" | head -n1 || true; }

if [ "$MODE" = "check" ]; then
  drift=0
  pv="$(pinned_version)"
  if [ "$pv" != "$PLATFORM_VERSION" ]; then
    printf 'DRIFT: pinned version "%s" != platform version "%s"\n' "${pv:-<none>}" "$PLATFORM_VERSION" >&2
    drift=1
  fi
  for f in "${manifest[@]}"; do
    if [ ! -f "${VENDOR_DIR}/${f}" ]; then
      printf 'DRIFT: missing vendored file %s\n' "${VENDOR_DIR}/${f}" >&2; drift=1; continue
    fi
    if ! diff -q "${PLATFORM}/spec/${f}" "${VENDOR_DIR}/${f}" >/dev/null 2>&1; then
      printf 'DRIFT: %s differs from platform spec/%s\n' "${VENDOR_DIR}/${f}" "$f" >&2; drift=1
    fi
  done
  if [ "$drift" -ne 0 ]; then
    printf 'platform-sync: service is BEHIND the platform spec — run `platform-sync.sh %s` and review.\n' "$PLATFORM" >&2
    exit 1
  fi
  printf 'platform-sync: in sync with platform %s — no drift.\n' "$PLATFORM_VERSION"
  exit 0
fi

# sync mode
mkdir -p "$VENDOR_DIR"
changed=0
for f in "${manifest[@]}"; do
  dest="${VENDOR_DIR}/${f}"
  mkdir -p "$(dirname "$dest")"
  if [ ! -f "$dest" ] || ! diff -q "${PLATFORM}/spec/${f}" "$dest" >/dev/null 2>&1; then
    cp "${PLATFORM}/spec/${f}" "$dest"; changed=$((changed+1)); printf '  updated %s\n' "$dest"
  fi
done

cat > "$CONFIG" <<EOF
# Generated by platform-sync.sh — pins this service to a platform spec version.
# The files in this directory are VENDORED, READ-ONLY copies of the platform spec.
# Do not edit them here; edit the spec in the platform repo and re-run platform-sync.sh.
PLATFORM_VERSION=${PLATFORM_VERSION}
EOF

if [ "$changed" -eq 0 ]; then
  printf 'platform-sync: already at platform %s — nothing to update.\n' "$PLATFORM_VERSION"
else
  printf 'platform-sync: synced %d file(s) to platform %s. Changes are UNSTAGED — review them in your PR.\n' "$changed" "$PLATFORM_VERSION"
fi
